version: 2.1

orbs: # declare what orbs we are going to use
  node: circleci/node@2.0.2
jobs:
  test:
    docker:
      - image: node:14.17.2
      - image: circleci/redis
      - image: circleci/postgres:11.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: whatsapp-test
          POSTGRES_PASSWORD: postgres
          TZ: 'Etc/UTC'

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Check install
          command: |
            node --version
            yarn --version

      - run:
          name: Install node modules
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Migrations
          command: npx prisma db push

      - run:
          name: Run Tests
          command: yarn test

    environment:
      TZ: 'Etc/UTC'
      NODE_ENV: "local"
      BASE_APP: "./src"
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/whatsapp-test?schema=public"
      PRIVATE_KEY: "Uvyno8HNbhvOp8qAHxbH0G8zZe4J26N6PHs6hZ1h"
    parallelism: 3

  hold:
    machine: true
    steps:
      - run: echo 'You must approve to deploy this branch'

  deploy:
    docker:
      - image: node:14.17.2
        # user: node

    steps:
      - checkout

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Check install
          command: |
            node --version
            yarn --version

      - run:
          name: Install node modules
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install railway
          command: chmod +x /usr/local/lib/node_modules

      - run:
          name: Install railway
          command: npm install -g @railway/cli
        
      - run:
          name: Run railway deploy
          command: RAILWAY_TOKEN=e83a9ae3-bb54-49bd-9391-76094154188f railway up

      #- run: 
      #    name: Install railway
      #    command: yarn global bin

      #- run: 
      #    name: Install railway
      #    command: export PATH="$PATH:`yarn global bin`"3

      #- run: 
      #    name: Install railway
      #    command: bash -l

      # - run:
      #     name: Start deploy to railway
      #     command: RAILWAY_TOKEN=e83a9ae3-bb54-49bd-9391-76094154188f railway up



workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold
